import { sequelize, Package } from './models/sqlModels.js';

const mockPackages = [
    // 🇮🇳 INDIA PACKAGES
    { title: "Beach Paradise Goa", destination: "Goa", country: "India", price: 65899, duration: "7 Days", popularityScore: 80, tags: "culture adventure beaches nightlife cuisine india asia", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600", description: "Golden beaches stretch endlessly alongside vibrant markets and aromatic spice-scented air, offering a perfect blend of relaxation and lively culture." },
    { title: "Explore Delhi Heritage", destination: "Delhi", country: "India", price: 32786, duration: "7 Days", popularityScore: 74, tags: "culture nightlife cuisine urban india asia", image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600", description: "Bustling streets filled with vibrant colors, diverse aromas, and the sounds of life create an energetic and unforgettable experience." },
    { title: "Historic Kolkata Tour", destination: "Kolkata", country: "India", price: 20693, duration: "7 Days", popularityScore: 71, tags: "culture cuisine urban india asia", image: "https://images.unsplash.com/photo-1558431382-27e30314225d?w=600", description: "Bustling streets filled with the aroma of spices, vibrant markets, and colonial architecture create an inviting atmosphere full of life and history." },
    { title: "Historic Jaipur Tour", destination: "Jaipur", country: "India", price: 24958, duration: "7 Days", popularityScore: 70, tags: "culture cuisine india asia", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600", description: "A tapestry of vibrant colors and bustling markets, where ancient forts and palaces echo the grandeur of a rich cultural heritage." },
    { title: "Cultural Journey to Mumbai", destination: "Mumbai", country: "India", price: 76823, duration: "7 Days", popularityScore: 69, tags: "culture nightlife cuisine urban india asia", image: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=600", description: "A bustling metropolis where vibrant street life, aromatic food stalls, and historic landmarks blend with a dynamic energy that never sleeps." },
    { title: "Cultural Journey to Jodhpur", destination: "Jodhpur", country: "India", price: 19622, duration: "4 Days", popularityScore: 67, tags: "culture cuisine india asia", image: "https://images.unsplash.com/photo-1534234828563-02597725459b?w=600", description: "Sun-drenched streets weave through vibrant markets and historic forts, offering a sensory journey rich with colors, aromas, and cultural warmth." },
    { title: "Ladakh Adventure Trip", destination: "Ladakh", country: "India", price: 24402, duration: "7 Days", popularityScore: 64, tags: "culture adventure nature seclusion india asia", image: "https://images.unsplash.com/photo-1581793434119-98f0afda66fd?w=600", description: "Rugged landscapes with towering mountains and serene monasteries create a tranquil yet awe-inspiring atmosphere, perfect for those seeking adventure and peace." },
    { title: "Explore Varanasi Heritage", destination: "Varanasi", country: "India", price: 29921, duration: "7 Days", popularityScore: 62, tags: "culture cuisine india asia", image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600", description: "Winding alleyways filled with the scent of incense and the sound of temple bells create a spiritual and vibrant atmosphere by the river." },
    { title: "Historic Amritsar Tour", destination: "Amritsar", country: "India", price: 26987, duration: "7 Days", popularityScore: 61, tags: "culture cuisine india asia", image: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=600", description: "Golden hues of the temple shimmer in the sun, while the aroma of spices and the hum of prayers create a serene, vibrant atmosphere." },

    // 🌏 GLOBAL PACKAGES
    { title: "Rio de Janeiro Green Getaway", destination: "Rio de Janeiro", country: "Brazil", price: 53966, duration: "7 Days", popularityScore: 90, tags: "culture adventure nature beaches nightlife cuisine urban brazil south_america", image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=600", description: "Vibrant streets pulse with samba rhythms, stunning beaches meet lush mountains, and every corner offers a burst of color and life." },
    { title: "Nature Escape in Honolulu", destination: "Honolulu", country: "United States", price: 194656, duration: "7 Days", popularityScore: 90, tags: "culture adventure nature beaches nightlife cuisine wellness urban united states oceania", image: "https://images.unsplash.com/photo-1542259548-262138ebdb77?w=600", description: "Golden beaches meet vibrant city life, where the scent of plumeria and the sounds of ukulele create a laid-back, tropical vibe." },
    { title: "Relaxing Sydney Coast", destination: "Sydney", country: "Australia", price: 157612, duration: "7 Days", popularityScore: 86, tags: "culture adventure nature beaches nightlife cuisine urban australia oceania", image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=600", description: "A lively harbor city where golden beaches meet urban sophistication, offering a blend of vibrant culture and stunning natural beauty." },
    { title: "Nature Escape in Moorea", destination: "Moorea", country: "French Polynesia", price: 190602, duration: "7 Days", popularityScore: 85, tags: "adventure nature beaches cuisine wellness seclusion french polynesia oceania", image: "https://images.unsplash.com/photo-1532408840135-2b363673b5df?w=600", description: "Lush green mountains meet turquoise lagoons, creating a serene paradise where gentle ocean breezes and vibrant coral reefs invite endless exploration." },
    { title: "Sun & Sand in San Diego", destination: "San Diego", country: "United States", price: 81156, duration: "7 Days", popularityScore: 84, tags: "culture adventure nature beaches nightlife cuisine wellness urban united states north_america", image: "https://images.unsplash.com/photo-1503891450247-ee5f8ec46dc3?w=600", description: "Sun-drenched beaches, vibrant neighborhoods, and an easygoing vibe invite you to savor ocean breezes and explore diverse, lively cultural spots." },
    { title: "Sun & Sand in Antalya", destination: "Antalya", country: "Turkey", price: 81383, duration: "7 Days", popularityScore: 84, tags: "culture adventure nature beaches nightlife cuisine wellness turkey asia", image: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600", description: "Sun-drenched beaches meet ancient ruins and bustling bazaars, offering a blend of relaxation and cultural exploration in a picturesque coastal setting." },
    { title: "Scenic Tahiti Tour", destination: "Tahiti", country: "French Polynesia", price: 181478, duration: "7 Days", popularityScore: 84, tags: "adventure nature beaches cuisine wellness seclusion french polynesia oceania", image: "https://images.unsplash.com/photo-1566375638419-7975871318f7?w=600", description: "Lush landscapes and tranquil lagoons invite a sense of serenity, where vibrant markets and local flavors add a touch of island warmth." },
    { title: "Explore Melbourne Heritage", destination: "Melbourne", country: "Australia", price: 87857, duration: "7 Days", popularityScore: 83, tags: "culture nightlife cuisine wellness urban australia oceania", image: "https://images.unsplash.com/photo-1514395462725-fb4566216a44?w=600", description: "A vibrant mix of street art, diverse cuisine, and lively laneways create an atmosphere that's both exciting and warmly inviting." },
    { title: "Historic Tuscany Tour", destination: "Tuscany", country: "Italy", price: 43212, duration: "7 Days", popularityScore: 83, tags: "culture nature cuisine wellness seclusion italy europe", image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600", description: "Rolling hills, sun-drenched vineyards, and charming medieval towns create a picturesque landscape that invites leisurely exploration and indulgent culinary experiences." },
    { title: "Historic Puglia Tour", destination: "Puglia", country: "Italy", price: 83981, duration: "7 Days", popularityScore: 83, tags: "culture nature beaches cuisine wellness seclusion italy europe", image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=600", description: "Sun-drenched coastlines, charming whitewashed villages, and the aroma of olive groves create a serene and inviting atmosphere." },
    { title: "Explore Hong Kong Heritage", destination: "Hong Kong", country: "Hong Kong", price: 226017, duration: "7 Days", popularityScore: 83, tags: "culture nightlife cuisine urban hong kong asia", image: "https://images.unsplash.com/photo-1506318137071-a8bcbf6755dd?w=600", description: "A bustling metropolis where neon lights reflect off harbor waters, offering a vibrant mix of street markets, towering skyscrapers, and serene parks." },
    { title: "Nature Escape in Nadi", destination: "Nadi", country: "Fiji", price: 75612, duration: "7 Days", popularityScore: 83, tags: "adventure nature beaches wellness seclusion fiji oceania", image: "https://images.unsplash.com/photo-1544473244-f6895e672d1a?w=600", description: "Tropical breezes and vibrant markets greet you, where lush greenery meets sandy beaches, creating a laid-back yet lively atmosphere." },
    { title: "Scenic Florianópolis Tour", destination: "Florianópolis", country: "Brazil", price: 80930, duration: "7 Days", popularityScore: 83, tags: "adventure nature beaches nightlife cuisine urban brazil south_america", image: "https://images.unsplash.com/photo-1564052600570-877292276527?w=600", description: "A blend of vibrant beaches, lush greenery, and lively markets creates a laid-back yet energetic vibe perfect for unwinding and exploring." },
    { title: "Scenic Hamilton Island Tour", destination: "Hamilton Island", country: "Australia", price: 189077, duration: "7 Days", popularityScore: 82, tags: "adventure nature beaches cuisine wellness seclusion australia oceania", image: "https://images.unsplash.com/photo-1526958097901-5e6d742d3371?w=600", description: "Turquoise waters and lush landscapes create a serene escape, where gentle sea breezes and vibrant sunsets offer a perfect island retreat." },
    { title: "Cultural Journey to Valencia", destination: "Valencia", country: "Spain", price: 84151, duration: "7 Days", popularityScore: 82, tags: "culture nature beaches nightlife cuisine urban spain europe", image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600", description: "Sun-drenched streets lined with orange trees, vibrant markets, and a seamless blend of ancient history and modern art create a captivating atmosphere." },
    { title: "Explore Sicily Heritage", destination: "Sicily", country: "Italy", price: 59554, duration: "7 Days", popularityScore: 82, tags: "culture nature beaches cuisine italy europe", image: "https://images.unsplash.com/photo-1555992828-ca4dbe41d294?w=600", description: "Sun-drenched landscapes, aromatic citrus groves, and vibrant markets create a sensory feast, while ancient ruins whisper stories of a rich, layered history." },
    { title: "Nature Escape in Crete", destination: "Crete", country: "Greece", price: 50373, duration: "7 Days", popularityScore: 82, tags: "culture adventure nature beaches cuisine wellness seclusion greece europe", image: "https://images.unsplash.com/photo-1515091943-9d5c0ad68ce7?w=600", description: "Sun-drenched beaches, ancient ruins, and vibrant local markets create a tapestry of experiences that feel both timeless and refreshingly alive." },
    { title: "Sardinia Green Getaway", destination: "Sardinia", country: "Italy", price: 65626, duration: "7 Days", popularityScore: 82, tags: "adventure nature beaches cuisine wellness seclusion italy europe", image: "https://images.unsplash.com/photo-1542397284385-6010376c5337?w=600", description: "Crystal-clear waters, rugged coastlines, and charming villages create a serene escape where you can unwind and savor local flavors." },
    { title: "Cebu Green Getaway", destination: "Cebu", country: "Philippines", price: 15155, duration: "7 Days", popularityScore: 82, tags: "adventure nature beaches cuisine philippines asia", image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=600", description: "Tropical warmth, vibrant street life, and a mix of modern and historic sites create an inviting atmosphere full of discovery and relaxation." },
    { title: "Party in Los Angeles", destination: "Los Angeles", country: "United States", price: 104857, duration: "7 Days", popularityScore: 82, tags: "culture beaches nightlife cuisine wellness urban united states north_america", image: "https://images.unsplash.com/photo-1503891450247-ee5f8ec46dc3?w=600", description: "Endless sunshine, diverse neighborhoods, and the allure of Hollywood create a dynamic atmosphere where every street feels like a new adventure." },
    { title: "Historic Athens Tour", destination: "Athens", country: "Greece", price: 84498, duration: "7 Days", popularityScore: 81, tags: "culture nightlife cuisine urban greece europe", image: "https://images.unsplash.com/photo-1505886918845-7e88295f1211?w=600", description: "Ancient ruins stand proudly against a backdrop of vibrant street life and bustling markets, where history and modernity create an electrifying blend." },
    { title: "Relaxing Bridgetown Coast", destination: "Bridgetown", country: "Barbados", price: 75554, duration: "7 Days", popularityScore: 81, tags: "nature beaches nightlife cuisine wellness barbados north_america", image: "https://images.unsplash.com/photo-1596203173775-8025287f7d1a?w=600", description: "Warm ocean breezes mingle with the rhythmic beats of calypso music, creating an inviting atmosphere perfect for unwinding and exploration." },
    { title: "Cultural Journey to Cartagena", destination: "Cartagena", country: "Colombia", price: 83403, duration: "7 Days", popularityScore: 81, tags: "culture beaches nightlife cuisine urban colombia south_america", image: "https://images.unsplash.com/photo-1583531352515-d59929848520?w=600", description: "Winding cobblestone streets, vibrant colonial architecture, and the rhythmic sound of salsa create a lively and colorful coastal atmosphere." },
    { title: "Scenic Bocas del Toro Tour", destination: "Bocas del Toro", country: "Panama", price: 82365, duration: "7 Days", popularityScore: 81, tags: "adventure nature beaches seclusion panama north_america", image: "https://images.unsplash.com/photo-1518182170546-07fa6dd17491?w=600", description: "Crystal-clear waters lap against palm-fringed beaches, while vibrant marine life and laid-back island vibes create an unforgettable tropical escape." },
    { title: "Sun & Sand in Zanzibar Town", destination: "Zanzibar Town", country: "Tanzania", price: 54968, duration: "7 Days", popularityScore: 81, tags: "culture nature beaches cuisine seclusion tanzania africa", image: "https://images.unsplash.com/photo-1534764831610-85f269555c8c?w=600", description: "Winding streets filled with the aroma of spices and the sound of Swahili music create an enchanting and vibrant atmosphere." },
    { title: "Beach Paradise Hvar", destination: "Hvar", country: "Croatia", price: 75946, duration: "7 Days", popularityScore: 81, tags: "nature beaches nightlife cuisine croatia europe", image: "https://images.unsplash.com/photo-1562681816-6512140402cc?w=600", description: "Sun-drenched beaches, fragrant lavender fields, and lively waterfronts create a vibrant yet relaxed atmosphere perfect for unwinding and exploring." },
    { title: "Scenic Bora Bora Tour", destination: "Bora Bora", country: "French Polynesia", price: 149708, duration: "7 Days", popularityScore: 81, tags: "adventure nature beaches wellness seclusion french polynesia oceania", image: "https://images.unsplash.com/photo-1532408840135-2b363673b5df?w=600", description: "Turquoise lagoons and lush green mountains create a serene paradise, where the gentle ocean breeze and vibrant sunsets captivate your senses." },
    { title: "Palawan Green Getaway", destination: "Palawan", country: "Philippines", price: 28737, duration: "7 Days", popularityScore: 81, tags: "adventure nature beaches seclusion philippines asia", image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=600", description: "Crystal-clear waters, lush green landscapes, and vibrant marine life create a serene escape where relaxation and adventure blend seamlessly." },
    { title: "Relaxing Punta del Este Coast", destination: "Punta del Este", country: "Uruguay", price: 59903, duration: "7 Days", popularityScore: 81, tags: "beaches nightlife cuisine urban uruguay south_america", image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=600", description: "Golden beaches meet vibrant nightlife, creating a lively yet laid-back atmosphere where ocean breezes, art, and music fill the air." },
    { title: "Nature Escape in Rarotonga", destination: "Rarotonga", country: "Cook Islands", price: 60764, duration: "7 Days", popularityScore: 81, tags: "adventure nature beaches wellness seclusion cook islands oceania", image: "https://images.unsplash.com/photo-1542259548-262138ebdb77?w=600", description: "Lush green mountains meet crystal-clear lagoons, offering a tranquil escape where the gentle rhythm of island life captivates your senses." },
    { title: "Nature Escape in Santa Marta", destination: "Santa Marta", country: "Colombia", price: 29536, duration: "7 Days", popularityScore: 81, tags: "culture adventure nature beaches cuisine seclusion colombia south_america", image: "https://images.unsplash.com/photo-1534945763267-332306283184?w=600", description: "Golden beaches meet lush mountains, creating a laid-back vibe where you can savor fresh seafood and vibrant sunsets by the sea." },
    { title: "Relaxing Key West Coast", destination: "Key West", country: "United States", price: 248990, duration: "4 Days", popularityScore: 81, tags: "adventure nature beaches nightlife cuisine united states north_america", image: "https://images.unsplash.com/photo-1535443274868-756b0f070b6e?w=600", description: "Sun-drenched streets with a laid-back vibe, vibrant art scenes, and ocean breezes create a carefree, tropical escape full of charm." },
    { title: "Scenic Savusavu Tour", destination: "Savusavu", country: "Fiji", price: 68127, duration: "7 Days", popularityScore: 81, tags: "adventure nature beaches wellness seclusion fiji oceania", image: "https://images.unsplash.com/photo-1544473244-f6895e672d1a?w=600", description: "Tucked away on a tranquil bay, this tropical haven offers lush landscapes, warm ocean breezes, and a welcoming, laid-back island vibe." },
    { title: "Historic Mexico City Tour", destination: "Mexico City", country: "Mexico", price: 72357, duration: "7 Days", popularityScore: 80, tags: "culture nightlife cuisine urban mexico north_america", image: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=600", description: "Vibrant streets teeming with life, colorful markets, and the aroma of street food create an eclectic and exhilarating urban experience." }
];

const seedDB = async () => {
    try {
        await sequelize.authenticate();
        
        // 🚨 BYPASS FOREIGN KEY ERROR: Turn checks OFF
        await sequelize.query('SET FOREIGN_KEY_CHECKS = 0');

        // Force Recreate Package Table
        await Package.sync({ force: true }); 

        // Turn checks ON
        await sequelize.query('SET FOREIGN_KEY_CHECKS = 1');

        // Insert Data
        await Package.bulkCreate(mockPackages);
        
        console.log("✅ Database Seeded with " + mockPackages.length + " Real Packages!");
        process.exit();
    } catch (err) {
        console.error("❌ Seeding Failed:", err);
        process.exit(1);
    }
};

seedDB();